name: MediaFlow Proxy CI/CD

on:
  push:
    branches: ["main"]

jobs:
  mediaflow_proxy_docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build & Push image
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 \
          -t notfullmetal/mediaflow-proxy:${{ env.SHORT_SHA }} \
          -t notfullmetal/mediaflow-proxy:${{ github.ref_name }} \
          -t notfullmetal/mediaflow-proxy:latest \
          . --push

